### ISSUE TITLE
[BD] tabela de usuário

### ISSUE THREAD

**Issue by Evelynsuzarte** [Squad-Katherine-Johnson-WoMakersCode/Desafiofinal-bootcampPythonDjango#22]

**Comment by milenamuch** [comment]
A tabela de usuários é a nativa do Django User, que já possui criptografia de senha e possibilita a alteração da role daquele usuário para admin ou somente User, no nosso coso o User é o Autor e terá autonomia somente sobre as suas próprias publicações.
